export const GET_CHAPTER_LIST = 'GET_CHAPTER_LIST'
export const GET_LESSON_LIST = 'GET_LESSON_LIST'
export const BATCH_DEL_CHAPTER = 'BATCH_DEL_CHAPTER'
export const BATCH_DEL_LESSON = 'BATCH_DEL_LESSON'
